### PR TITLE
Added some libraries

### PR DESCRIPTION
**Pull request by Alexiril**
**Hi again :)**

Alright, that's what I did:

- Added newtonsoft Json package (needed for Photon Unity Networking)

- Added UnityEditor.dll and UnityEngine.dll (version 5.5.0) By the way, got the version from the dev version game, from the file output_log.txt, like first line contains the unity version.

- Added Standard assets image effects

- Added and fixed (yeah, it wasn't working correctly by itself) Spline. Fixed around 80 files of game code to be compatible with the downloaded Spline version. Being honest, not sure if it is the best package version, I don't know what version of Spline editor was used to create the animation, so, not sure what version is the best choice.

- Added SEGI (visual effect). That was easy, little fixes only.

- Added PostProcessing unity stuff.

- Fixed Photon Unity Networking, weird things with versions. (For some reason it was manage unity scenes, like SceneManager class. Removed it, there is an actual SceneManager class in Unity, the Photon one generated strange errors.)

- Added LipSync-Pro.

- Added CircularGravityForce. Fixed some version stuff, not sure if it will work correctly, I had to comment some physical stuff, may work odd.

A lot of code is still not working, to make it work we need other libraries :)

### CODE REVIEW

**Comment by Sollace** [comment]
Ah nice

Also I'm curious, is it normal practice for projects to include the full source code of any unity plugins/packages they use?
If this were anywhere else, I'd expect them to be distributed as dlls more similar to nuget packages.

**Comment by Alexiril** [comment]
Well, I'm not sure, how it's done in all Unity projects. But in the projects I was working on, usually most packages were sources, distributed as unitypackage files (like archives). However, at times, some libraries included both source code and libraries. But the libraries were not made in C#, and were a specific implementation for a specific platform (both .dll libraries and .so libraries).
Even though, I think, it is possible to compile the entire plugin apart the main code of the game and use as dll. Except assets, of course. Just in this case does it matter? The sources I added are about 60 megabytes, not that much.

**Comment by Sollace** [comment]
Yeah doesn't matter much. If it's the way most people handle their unity projects, I'm fine with it.

**Comment by Sollace** [comment]
Gonna go ahead and merge this now.

**Pull request merged**
