### PR TITLE
New libs

### PR DESCRIPTION
**Pull request by Alexiril**
**Hey! More libs here :)**

I've included those libraries:

- Trail Effect (the author of the source used Git LFS weirdly, we cannot get some images, maybe a problem later)
- TextMesh Pro
- Colorful FX
- Cinema Director
- Particle Playground
- Highlighting System
- Control Mapper (Rewired)
- PopcornFX

### CODE REVIEW

**Comment by Sollace** [comment]
Ah yes, Git LFS... The bane of everyone's existance.

I had to go through this when github shut off lfs for this repository. In short, to get the files, what you have to do is fork the repository to your own account and then, turn on "include git lfs" files in the setting and archive it. Then you can use the "download as zip" option after rather than cloning it and you'll get everything.

From [stackoverflow](https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh)
1. Fork the repo to one of your users
2. Go to repo settings
3. Find "Include Git LFS objects in archives" under the Archives section and check it
4. Go to the Danger Zone section, select "Archive this repository"
5. Confirm and authorize.
6. Return to the archived repository.
7. Download as .zip

Download will pause for a minute or so before it starts downloading lfs objects. Wait and it should continue.

**Comment by Alexiril** [comment]
Yeah, you were absolutely right about LFS, I've done it like you recommended, and now we have those images :)

**Comment by Sollace** [comment]
Is it okay if I merge this one now, or do you have more you want to add?

**Comment by Alexiril** [comment]
Well, let's wait till tomorrow - I hope, I will be able to finish this library challenge in 15 hours :)

**Comment by Alexiril** [comment]
Alright, I added the last libraries and now the code doesn't have errors. But! I had to comment out the sections with WordPress for Unity (MBS, WUlogin).

**Comment by Sollace** [comment]
That should be fine. I can't think of anything we'd need wordpress for.

**Pull request merged**
