### PR TITLE
Added scenes and fixed Fie.User namespace

### PR DESCRIPTION
**Pull request by Alexiril**
Added unpacked scenes from the developer version of game. They look correct in unity (used Unity 5.6 to check scenes, and Unity 2020.2.7 to check the code). Fixed Fie.User namespace error. The project is still not buildable, due to a lot of errors. I couldn't find popcornfx v1 for unity that was used in the project, and I don't have cinema director ($30).

### CODE REVIEW

**Comment by Sollace** [comment]
Excellent work! Thanks a lot.

**Comment by Sollace** [comment]
If we can't find popcornfx, as a last resort you can give me an idea what namespaces the classes for it are in and I can try pulling it from the developer version as well.

When it was originally built Unity seems to roll everything together in the same dll, so all the plugins' classes can be found in there as well if you know what to look for.

**Comment by Alexiril** [comment]
**Hello again :)** 

I've analyzed the code and found out some lost libraries. Some of them are still available (though, the new versions probably won't work correct). Others are just lost somewhere on the internet :)

So, paid libraries / namespaces that I don't have, unfortunately:

- CircularGravityForce
- ParticlePlayground
- CinemaDirector
- HighlightingSystem

Some free libs / namespaces:

- TMPro
- Spine.Unity
- Spine (?)

And unknown, or I just didn't understand:

- RogoDigital.Lipsync
- PigeonCoopToolkit.Effect.Trails
- Colorful

The weird thing is about spine. I downloaded different versions of the lib and tried from the oldest available (3.6 or something) to the newest. All the versions were showing same errors, they like didn't have base classes (Skeleton, Bone). I didn't use spine plugin for unity before and don't know why it doesn't work.

By the way, some odd errors occur due to the unity version. The photon library, for example, didn't work correctly, because inside the code, developers didn't expect unity version newer 5.5. I will look closer for correct versions of unity, probably UnityEngine.dll and UnityEditor.dll versions are really important. As an example, namespaces PostProcessing and UnityStandardAssets don't work in newer versions of Unity.

**Comment by Sollace** [comment]
Identifying the exact version of unity would be very helpful. I wasn't able to find anything looking at the version info on the dlls (they just say 0.0.0.0) but I did include all of them in the packages directory anyway so at least I could link them in visual studio.

If it's okay with you, can I make some separate tickets with all of this so we can keep track of it?

**Comment by Sollace** [comment]
Alright, put what I can into an issue over here: https://github.com/FriendshipIsEpic/FiE-Game/issues/3

**Comment by Sollace** [comment]
>  downloaded different versions of the lib and tried from the oldest available (3.6 or something) to the newest. All the versions 

were showing same errors, they like didn't have base classes
That's a strong indication that you might have run into a different lib with the same name. So maybe look for other things named Spine?

**Comment by Sollace** [comment]
The spine I found and linked on #3 does appear to have the required classes. https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-csharp/src/Skeleton.cs

**Pull request merged**
